name: firefriday
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.1
  file_picker: ^8.0.2
  firebase_auth: ^4.19.2
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  pdf: ^3.10.8
  printing: ^5.12.0
  routerino: ^0.8.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  stylish_dialog: ^1.0.2
  toastification: ^2.0.0
  unicons: ^2.1.1
  url_launcher: ^6.2.6
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/uzlogo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/logo/
